name: test

on:
  push

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # Required for release creation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract tag version
      id: version
      shell: pwsh
      run: |
        $version = $env:GITHUB_SHA.Substring(0, 7)
        echo "VERSION=$version" >> $env:GITHUB_ENV

    - name: Prepare build dir
      shell: powershell
      run: |
        $dest = "${{ github.workspace }}\VibepolloFleet"
        New-Item -ItemType Directory -Force -Path $dest
        Copy-Item -Path "${{ github.workspace }}\README.md" -Destination $dest
        Copy-Item -Path "${{ github.workspace }}\bin" -Destination $dest -Recurse

    - name: Compile AHK script
      uses: drajabr/Action-Ahk2Exe@main
      with:
        in: Vibepollo Fleet.ahk
        out: ${{ github.workspace }}/VibepolloFleet/VibepolloFleet.exe  # Use a fixed name during compilation
        icon: ${{ github.workspace }}/icons/9.ico

    - name: Create SFX Zip installer
      uses: drajabr/actions-7-zip-win@main
      with:
        in: ${{ github.workspace }}\VibepolloFleet
        out: ${{ github.workspace }}\VibepolloFleet-${{ env.VERSION }}.exe
        options: a -sfx7z.sfx

    - name: List All files
      run: |
          echo "Files in /VibepolloFleet:"
          Get-ChildItem -Path VibepolloFleet -Recurse
      shell: pwsh

    - name: Upload test build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VibepolloFleet-${{ env.VERSION }}.exe
        path: "${{ github.workspace }}\\VibepolloFleet-${{ env.VERSION }}.exe"